export const organizations = [
    "Aucune",
    "Insee",
    "SSP/Srise - Agriculture et alimentation",
    "DESL - Collectivités locales",
    "DSECE - Commerce extérieur",
    "Deps - Culture",
    "S2E - Défense",
    "Sdes - Énergie, logement, transport, environnement",
    "Depp - Éducation",
    "Sies - Enseignement supérieur, recherche",
    "PSP - Finances publiques",
    "Sdessi - Fonction publique",
    "DSED - Immigration",
    "Medes - Jeunesse et sports",
    "SSER - Justice",
    "Drees - Santé et solidarités",
    "SSMSI - Sécurité intérieure",
    "Dares - Travail"
];
